name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo apt-get install portaudio19-dev
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit -r . || true
      - run: black --check .
      - run: codespell --quiet-level=2  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --show-source --statistics
      - run: isort --check-only --profile black .
      - run: pip install -r requirements.txt
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
